/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as PhotosEventRouteImport } from './routes/photos.event'
import { Route as PhotosFaceRouteImport } from './routes/photos.face'
import { Route as PhotosPhoneRouteImport } from './routes/photos.phone'
import { Route as PhotosQrRouteImport } from './routes/photos.qr'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalForgotPasswordRouteImport } from './routes/portal.forgot-password'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalResetPasswordRouteImport } from './routes/portal.reset-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiMediaPhotoIdRouteImport } from './routes/api/media.$photoId'
import { Route as ApiPortalClaimOwnerRouteImport } from './routes/api/portal.claim-owner'
import { Route as ApiPortalLoginHealthRouteImport } from './routes/api/portal.login-health'
import { Route as ApiPortalStorageHealthRouteImport } from './routes/api/portal.storage-health'
import { Route as ApiPortalUploadRouteImport } from './routes/api/portal.upload'
import { Route as PortalEventsIdRouteImport } from './routes/portal.events.$id'
import { Route as PortalEventsNewRouteImport } from './routes/portal.events.new'
import { Route as PrintCodeCodeRouteImport } from './routes/print.code.$code'
import { Route as PortalEventsIdEditRouteImport } from './routes/portal.events.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosEventRoute = PhotosEventRouteImport.update({
  id: '/photos/event',
  path: '/photos/event',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosFaceRoute = PhotosFaceRouteImport.update({
  id: '/photos/face',
  path: '/photos/face',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhoneRoute = PhotosPhoneRouteImport.update({
  id: '/photos/phone',
  path: '/photos/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosQrRoute = PhotosQrRouteImport.update({
  id: '/photos/qr',
  path: '/photos/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalForgotPasswordRoute = PortalForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalResetPasswordRoute = PortalResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaPhotoIdRoute = ApiMediaPhotoIdRouteImport.update({
  id: '/api/media/$photoId',
  path: '/api/media/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalClaimOwnerRoute = ApiPortalClaimOwnerRouteImport.update({
  id: '/api/portal/claim-owner',
  path: '/api/portal/claim-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalLoginHealthRoute = ApiPortalLoginHealthRouteImport.update({
  id: '/api/portal/login-health',
  path: '/api/portal/login-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalStorageHealthRoute = ApiPortalStorageHealthRouteImport.update({
  id: '/api/portal/storage-health',
  path: '/api/portal/storage-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortalUploadRoute = ApiPortalUploadRouteImport.update({
  id: '/api/portal/upload',
  path: '/api/portal/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEventsIdRoute = PortalEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsNewRoute = PortalEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => PortalRoute,
} as any)
const PrintCodeCodeRoute = PrintCodeCodeRouteImport.update({
  id: '/print/code/$code',
  path: '/print/code/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEventsIdEditRoute = PortalEventsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PortalEventsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/explore': typeof ExploreRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/photos/event': typeof PhotosEventRoute
  '/photos/face': typeof PhotosFaceRoute
  '/photos/phone': typeof PhotosPhoneRoute
  '/photos/qr': typeof PhotosQrRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/events/': typeof EventsIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$photoId': typeof ApiMediaPhotoIdRoute
  '/api/portal/claim-owner': typeof ApiPortalClaimOwnerRoute
  '/api/portal/login-health': typeof ApiPortalLoginHealthRoute
  '/api/portal/storage-health': typeof ApiPortalStorageHealthRoute
  '/api/portal/upload': typeof ApiPortalUploadRoute
  '/portal/events/$id': typeof PortalEventsIdRouteWithChildren
  '/portal/events/new': typeof PortalEventsNewRoute
  '/print/code/$code': typeof PrintCodeCodeRoute
  '/portal/events/$id/edit': typeof PortalEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/explore': typeof ExploreRoute
  '/privacy': typeof PrivacyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/photos/event': typeof PhotosEventRoute
  '/photos/face': typeof PhotosFaceRoute
  '/photos/phone': typeof PhotosPhoneRoute
  '/photos/qr': typeof PhotosQrRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/events': typeof EventsIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$photoId': typeof ApiMediaPhotoIdRoute
  '/api/portal/claim-owner': typeof ApiPortalClaimOwnerRoute
  '/api/portal/login-health': typeof ApiPortalLoginHealthRoute
  '/api/portal/storage-health': typeof ApiPortalStorageHealthRoute
  '/api/portal/upload': typeof ApiPortalUploadRoute
  '/portal/events/$id': typeof PortalEventsIdRouteWithChildren
  '/portal/events/new': typeof PortalEventsNewRoute
  '/print/code/$code': typeof PrintCodeCodeRoute
  '/portal/events/$id/edit': typeof PortalEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/explore': typeof ExploreRoute
  '/portal': typeof PortalRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/photos/event': typeof PhotosEventRoute
  '/photos/face': typeof PhotosFaceRoute
  '/photos/phone': typeof PhotosPhoneRoute
  '/photos/qr': typeof PhotosQrRoute
  '/portal/forgot-password': typeof PortalForgotPasswordRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/reset-password': typeof PortalResetPasswordRoute
  '/events/': typeof EventsIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/media/$photoId': typeof ApiMediaPhotoIdRoute
  '/api/portal/claim-owner': typeof ApiPortalClaimOwnerRoute
  '/api/portal/login-health': typeof ApiPortalLoginHealthRoute
  '/api/portal/storage-health': typeof ApiPortalStorageHealthRoute
  '/api/portal/upload': typeof ApiPortalUploadRoute
  '/portal/events/$id': typeof PortalEventsIdRouteWithChildren
  '/portal/events/new': typeof PortalEventsNewRoute
  '/print/code/$code': typeof PrintCodeCodeRoute
  '/portal/events/$id/edit': typeof PortalEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/creators'
    | '/explore'
    | '/portal'
    | '/privacy'
    | '/events/$slug'
    | '/photos/event'
    | '/photos/face'
    | '/photos/phone'
    | '/photos/qr'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/reset-password'
    | '/events/'
    | '/photos/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/media/$photoId'
    | '/api/portal/claim-owner'
    | '/api/portal/login-health'
    | '/api/portal/storage-health'
    | '/api/portal/upload'
    | '/portal/events/$id'
    | '/portal/events/new'
    | '/print/code/$code'
    | '/portal/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creators'
    | '/explore'
    | '/privacy'
    | '/events/$slug'
    | '/photos/event'
    | '/photos/face'
    | '/photos/phone'
    | '/photos/qr'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/reset-password'
    | '/events'
    | '/photos'
    | '/portal'
    | '/api/auth/$'
    | '/api/media/$photoId'
    | '/api/portal/claim-owner'
    | '/api/portal/login-health'
    | '/api/portal/storage-health'
    | '/api/portal/upload'
    | '/portal/events/$id'
    | '/portal/events/new'
    | '/print/code/$code'
    | '/portal/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/creators'
    | '/explore'
    | '/portal'
    | '/privacy'
    | '/events/$slug'
    | '/photos/event'
    | '/photos/face'
    | '/photos/phone'
    | '/photos/qr'
    | '/portal/forgot-password'
    | '/portal/login'
    | '/portal/reset-password'
    | '/events/'
    | '/photos/'
    | '/portal/'
    | '/api/auth/$'
    | '/api/media/$photoId'
    | '/api/portal/claim-owner'
    | '/api/portal/login-health'
    | '/api/portal/storage-health'
    | '/api/portal/upload'
    | '/portal/events/$id'
    | '/portal/events/new'
    | '/print/code/$code'
    | '/portal/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  ExploreRoute: typeof ExploreRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  EventsSlugRoute: typeof EventsSlugRoute
  PhotosEventRoute: typeof PhotosEventRoute
  PhotosFaceRoute: typeof PhotosFaceRoute
  PhotosPhoneRoute: typeof PhotosPhoneRoute
  PhotosQrRoute: typeof PhotosQrRoute
  EventsIndexRoute: typeof EventsIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMediaPhotoIdRoute: typeof ApiMediaPhotoIdRoute
  ApiPortalClaimOwnerRoute: typeof ApiPortalClaimOwnerRoute
  ApiPortalLoginHealthRoute: typeof ApiPortalLoginHealthRoute
  ApiPortalStorageHealthRoute: typeof ApiPortalStorageHealthRoute
  ApiPortalUploadRoute: typeof ApiPortalUploadRoute
  PrintCodeCodeRoute: typeof PrintCodeCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/event': {
      id: '/photos/event'
      path: '/photos/event'
      fullPath: '/photos/event'
      preLoaderRoute: typeof PhotosEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/face': {
      id: '/photos/face'
      path: '/photos/face'
      fullPath: '/photos/face'
      preLoaderRoute: typeof PhotosFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/phone': {
      id: '/photos/phone'
      path: '/photos/phone'
      fullPath: '/photos/phone'
      preLoaderRoute: typeof PhotosPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/qr': {
      id: '/photos/qr'
      path: '/photos/qr'
      fullPath: '/photos/qr'
      preLoaderRoute: typeof PhotosQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/forgot-password': {
      id: '/portal/forgot-password'
      path: '/forgot-password'
      fullPath: '/portal/forgot-password'
      preLoaderRoute: typeof PortalForgotPasswordRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/reset-password': {
      id: '/portal/reset-password'
      path: '/reset-password'
      fullPath: '/portal/reset-password'
      preLoaderRoute: typeof PortalResetPasswordRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$photoId': {
      id: '/api/media/$photoId'
      path: '/api/media/$photoId'
      fullPath: '/api/media/$photoId'
      preLoaderRoute: typeof ApiMediaPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/claim-owner': {
      id: '/api/portal/claim-owner'
      path: '/api/portal/claim-owner'
      fullPath: '/api/portal/claim-owner'
      preLoaderRoute: typeof ApiPortalClaimOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/login-health': {
      id: '/api/portal/login-health'
      path: '/api/portal/login-health'
      fullPath: '/api/portal/login-health'
      preLoaderRoute: typeof ApiPortalLoginHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/storage-health': {
      id: '/api/portal/storage-health'
      path: '/api/portal/storage-health'
      fullPath: '/api/portal/storage-health'
      preLoaderRoute: typeof ApiPortalStorageHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portal/upload': {
      id: '/api/portal/upload'
      path: '/api/portal/upload'
      fullPath: '/api/portal/upload'
      preLoaderRoute: typeof ApiPortalUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/events/$id': {
      id: '/portal/events/$id'
      path: '/events/$id'
      fullPath: '/portal/events/$id'
      preLoaderRoute: typeof PortalEventsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/events/new': {
      id: '/portal/events/new'
      path: '/events/new'
      fullPath: '/portal/events/new'
      preLoaderRoute: typeof PortalEventsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/print/code/$code': {
      id: '/print/code/$code'
      path: '/print/code/$code'
      fullPath: '/print/code/$code'
      preLoaderRoute: typeof PrintCodeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/events/$id/edit': {
      id: '/portal/events/$id/edit'
      path: '/edit'
      fullPath: '/portal/events/$id/edit'
      preLoaderRoute: typeof PortalEventsIdEditRouteImport
      parentRoute: typeof PortalEventsIdRoute
    }
  }
}

interface PortalEventsIdRouteChildren {
  PortalEventsIdEditRoute: typeof PortalEventsIdEditRoute
}

const PortalEventsIdRouteChildren: PortalEventsIdRouteChildren = {
  PortalEventsIdEditRoute: PortalEventsIdEditRoute,
}

const PortalEventsIdRouteWithChildren = PortalEventsIdRoute._addFileChildren(
  PortalEventsIdRouteChildren,
)

interface PortalRouteChildren {
  PortalForgotPasswordRoute: typeof PortalForgotPasswordRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalResetPasswordRoute: typeof PortalResetPasswordRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalEventsIdRoute: typeof PortalEventsIdRouteWithChildren
  PortalEventsNewRoute: typeof PortalEventsNewRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalForgotPasswordRoute: PortalForgotPasswordRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalResetPasswordRoute: PortalResetPasswordRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalEventsIdRoute: PortalEventsIdRouteWithChildren,
  PortalEventsNewRoute: PortalEventsNewRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  ExploreRoute: ExploreRoute,
  PortalRoute: PortalRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  EventsSlugRoute: EventsSlugRoute,
  PhotosEventRoute: PhotosEventRoute,
  PhotosFaceRoute: PhotosFaceRoute,
  PhotosPhoneRoute: PhotosPhoneRoute,
  PhotosQrRoute: PhotosQrRoute,
  EventsIndexRoute: EventsIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMediaPhotoIdRoute: ApiMediaPhotoIdRoute,
  ApiPortalClaimOwnerRoute: ApiPortalClaimOwnerRoute,
  ApiPortalLoginHealthRoute: ApiPortalLoginHealthRoute,
  ApiPortalStorageHealthRoute: ApiPortalStorageHealthRoute,
  ApiPortalUploadRoute: ApiPortalUploadRoute,
  PrintCodeCodeRoute: PrintCodeCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
