/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorsRouteImport } from './routes/creators'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as PhotosIndexRouteImport } from './routes/photos.index'
import { Route as PhotosEventRouteImport } from './routes/photos.event'
import { Route as PhotosFaceRouteImport } from './routes/photos.face'
import { Route as PhotosPhoneRouteImport } from './routes/photos.phone'
import { Route as PhotosQrRouteImport } from './routes/photos.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsRoute = CreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosEventRoute = PhotosEventRouteImport.update({
  id: '/photos/event',
  path: '/photos/event',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosFaceRoute = PhotosFaceRouteImport.update({
  id: '/photos/face',
  path: '/photos/face',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhoneRoute = PhotosPhoneRouteImport.update({
  id: '/photos/phone',
  path: '/photos/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosQrRoute = PhotosQrRouteImport.update({
  id: '/photos/qr',
  path: '/photos/qr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/explore': typeof ExploreRoute
  '/privacy': typeof PrivacyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/photos/event': typeof PhotosEventRoute
  '/photos/face': typeof PhotosFaceRoute
  '/photos/phone': typeof PhotosPhoneRoute
  '/photos/qr': typeof PhotosQrRoute
  '/events/': typeof EventsIndexRoute
  '/photos/': typeof PhotosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/explore': typeof ExploreRoute
  '/privacy': typeof PrivacyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/photos/event': typeof PhotosEventRoute
  '/photos/face': typeof PhotosFaceRoute
  '/photos/phone': typeof PhotosPhoneRoute
  '/photos/qr': typeof PhotosQrRoute
  '/events': typeof EventsIndexRoute
  '/photos': typeof PhotosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/creators': typeof CreatorsRoute
  '/explore': typeof ExploreRoute
  '/privacy': typeof PrivacyRoute
  '/events/$slug': typeof EventsSlugRoute
  '/photos/event': typeof PhotosEventRoute
  '/photos/face': typeof PhotosFaceRoute
  '/photos/phone': typeof PhotosPhoneRoute
  '/photos/qr': typeof PhotosQrRoute
  '/events/': typeof EventsIndexRoute
  '/photos/': typeof PhotosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/creators'
    | '/explore'
    | '/privacy'
    | '/events/$slug'
    | '/photos/event'
    | '/photos/face'
    | '/photos/phone'
    | '/photos/qr'
    | '/events/'
    | '/photos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/creators'
    | '/explore'
    | '/privacy'
    | '/events/$slug'
    | '/photos/event'
    | '/photos/face'
    | '/photos/phone'
    | '/photos/qr'
    | '/events'
    | '/photos'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/creators'
    | '/explore'
    | '/privacy'
    | '/events/$slug'
    | '/photos/event'
    | '/photos/face'
    | '/photos/phone'
    | '/photos/qr'
    | '/events/'
    | '/photos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  CreatorsRoute: typeof CreatorsRoute
  ExploreRoute: typeof ExploreRoute
  PrivacyRoute: typeof PrivacyRoute
  EventsSlugRoute: typeof EventsSlugRoute
  PhotosEventRoute: typeof PhotosEventRoute
  PhotosFaceRoute: typeof PhotosFaceRoute
  PhotosPhoneRoute: typeof PhotosPhoneRoute
  PhotosQrRoute: typeof PhotosQrRoute
  EventsIndexRoute: typeof EventsIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators': {
      id: '/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof CreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/event': {
      id: '/photos/event'
      path: '/photos/event'
      fullPath: '/photos/event'
      preLoaderRoute: typeof PhotosEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/face': {
      id: '/photos/face'
      path: '/photos/face'
      fullPath: '/photos/face'
      preLoaderRoute: typeof PhotosFaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/phone': {
      id: '/photos/phone'
      path: '/photos/phone'
      fullPath: '/photos/phone'
      preLoaderRoute: typeof PhotosPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/qr': {
      id: '/photos/qr'
      path: '/photos/qr'
      fullPath: '/photos/qr'
      preLoaderRoute: typeof PhotosQrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  CreatorsRoute: CreatorsRoute,
  ExploreRoute: ExploreRoute,
  PrivacyRoute: PrivacyRoute,
  EventsSlugRoute: EventsSlugRoute,
  PhotosEventRoute: PhotosEventRoute,
  PhotosFaceRoute: PhotosFaceRoute,
  PhotosPhoneRoute: PhotosPhoneRoute,
  PhotosQrRoute: PhotosQrRoute,
  EventsIndexRoute: EventsIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
